name: Release

env:
  PKG_VERSION: "2026.07.11-1"
  XCADDY_URL: https://github.com/caddyserver/xcaddy/releases/download/v0.4.5/xcaddy_0.4.5_linux_amd64.tar.gz
  XCADDY_SUM: sha256:2f96dde11b8ecbb7d652c20e05fddbfd2f58c622b464104309eae512406193cf

  # Preview mode: Publishes the build output as a CI artifact instead of creating
  # a release, allowing for manual inspection of the output. This mode is
  # activated if the CI run was triggered by events other than pushed tags, or
  # if the repository is a fork.
  preview: ${{ !startsWith(github.ref, 'refs/tags/') || github.repository != 'ci-prebuild/caddy' }}

on:
  push:
    tags:
    - '[0-9]+.[0-9]+'
    - '[0-9]+.[0-9]+.[0-9]+'
    branches:
    - 'patch/ci-release-*'
    - 'main'
  pull_request:
    paths:
    - '.github/workflows/release.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  build:
    name: Build ${{ matrix.build }}
    env:
      # Emit backtraces on panics.
      RUST_BACKTRACE: 1
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # don't fail other jobs if one fails
      matrix:
        build: [amd64, arm64]
        include:
        - build: amd64
          # WARN: When changing this to a newer version, make sure that the GLIBC isnt too new, as this can cause issues
          # with portablity on older systems that dont follow ubuntus more rapid release cadence.
          os: ubuntu-22.04
        - build: arm64
          # Version should be kept in lockstep with the x86_64 version
          os: ubuntu-22.04

    steps:
      - name: Checkout sources for packaging
        uses: actions/checkout@v7
        with:
          path: "__CI_PREBUILD__"

      - uses: actions/setup-go@v6
        with:
          go-version: 1.26.3
          cache: false
      - name: Prepare dist folder
        run: |
          mkdir -p dist
          cat <<EOF >>$GITHUB_ENV
          CADDY_BIN=dist/caddy_${{ env.PKG_VERSION }}_${{ matrix.build }}
          CADDY_L4_BIN=dist/caddy-l4_${{ env.PKG_VERSION }}_${{ matrix.build }}
          EOF
      - name: Download xcaddy
        run: |
          curl -L "${{ env.XCADDY_URL }}" -o xcaddy.tar.gz
          tar -zxvf xcaddy.tar.gz xcaddy

      # build deb action does not support arm runner so
      # we cross-compile
      - name: Build caddy-l4
        run: |
          GOARCH=${{ matrix.build }} ./xcaddy build --with github.com/mholt/caddy-l4
          cp caddy "$CADDY_L4_BIN"
          mkdir -p __CI_PREBUILD__/debian/caddy-l4/usr/local/bin
          cp caddy __CI_PREBUILD__/debian/caddy-l4/usr/local/bin/
      - name: Build mainline caddy
        run: |
          GOARCH=${{ matrix.build }} ./xcaddy build
          cp caddy "$CADDY_BIN"
          mkdir -p __CI_PREBUILD__/debian/caddy/usr/local/bin
          cp caddy __CI_PREBUILD__/debian/caddy/usr/local/bin/

      - name: Build caddy-l4 deb
        uses: jiro4989/build-deb-action@86e86ceb88b13157fa569663d43c89346505fc3e
        with:
          package: caddy-l4
          package_root: __CI_PREBUILD__/debian/caddy-l4
          maintainer: selfhoster1312
          version: ${{ env.PKG_VERSION }}
          arch: ${{ matrix.build }}
        id: build-deb-caddy-l4

      - name: Build caddy mainline deb
        uses: jiro4989/build-deb-action@86e86ceb88b13157fa569663d43c89346505fc3e
        with:
          package: caddy
          package_root: __CI_PREBUILD__/debian/caddy
          maintainer: selfhoster1312
          version: ${{ env.PKG_VERSION }}
          arch: ${{ matrix.build }}
        id: build-deb-caddy

      - name: Upload ${{ env.CADDY_BIN }} to artifacts
        uses: actions/upload-artifact@v7
        if: env.preview == 'true'
        with:
          path: ${{ env.CADDY_BIN }}
          archive: false
          if-no-files-found: error
      - name: Upload ${{ env.CADDY_L4_BIN }} to artifacts
        uses: actions/upload-artifact@v7
        if: env.preview == 'true'
        with:
          path: ${{ env.CADDY_L4_BIN }}
          archive: false
          if-no-files-found: error
      - name: Upload caddy deb to artifacts
        uses: actions/upload-artifact@v7
        if: env.preview == 'true'
        with:
          path: ${{ steps.build-deb-caddy.outputs.file_name }}
          archive: false
          if-no-files-found: error
      - name: Upload caddy-l4 deb to artifacts
        uses: actions/upload-artifact@v7
        if: env.preview == 'true'
        with:
          path: ${{ steps.build-deb-caddy-l4.outputs.file_name }}
          archive: false
          if-no-files-found: error

      - name: Upload ${{ env.CADDY_BIN }} to release
        uses: svenstaro/upload-release-action@29e53e917877a24fad85510ded594ab3c9ca12de # 2.11.5
        if: env.preview == 'false'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.CADDY_BIN }}
          tag: ${{ github.ref_name }}
          overwrite: true
      - name: Upload ${{ env.CADDY_L4_BIN }} to release
        uses: svenstaro/upload-release-action@29e53e917877a24fad85510ded594ab3c9ca12de # 2.11.5
        if: env.preview == 'false'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.CADDY_L4_BIN }}
          tag: ${{ github.ref_name }}
          overwrite: true
      - name: Upload caddy deb to release
        uses: svenstaro/upload-release-action@29e53e917877a24fad85510ded594ab3c9ca12de # 2.11.5
        if: env.preview == 'false'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ steps.build-deb-caddy.outputs.file_name }}
          tag: ${{ github.ref_name }}
          overwrite: true
      - name: Upload caddy-l4 deb to release
        uses: svenstaro/upload-release-action@29e53e917877a24fad85510ded594ab3c9ca12de # 2.11.5
        if: env.preview == 'false'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ steps.build-deb-caddy-l4.outputs.file_name }}
          tag: ${{ github.ref_name }}
          overwrite: true
